kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.env.name }}"
  namespace: {{ .Values.env.namespace.compute }}
rules:
- apiGroups:
  - "distributed-compute.dominodatalab.com"
  resources:
  - "rayclusters"
  - "sparkclusters"
  - "daskclusters"
  verbs:
  - "*"
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]